In [114]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
import random
from keras import losses, optimizers

In [115]:
# Cargar datos desde CSV
data = pd.read_csv('C:/Users/LEHI/Documents/Practicas profesionales/ABRIL/preprocessed data 33 columnas - etiqueta letras.csv')



In [116]:
df_uniq = data.groupby('clase').head(20)

In [117]:
#df_uniq

In [118]:
# Dividir los datos en características (X) y etiquetas (y)
X = df_uniq.drop('clase', axis=1)
y = df_uniq['clase']

In [119]:
# Convertir etiquetas a números
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [120]:
# Dividir datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar los datos (opcional pero recomendado)
X_train = (X_train - X_train.mean()) / X_train.std()
X_test = (X_test - X_test.mean()) / X_test.std()

In [121]:
# Definir la arquitectura de la red siamesa
input_shape = X_train.shape[1]


In [122]:
# Definir función para crear la rama de la red siamesa
def create_siamese_branch(input_shape):
    input_layer = tf.keras.layers.Input(shape=(input_shape,))
    x = tf.keras.layers.Dense(64, activation='relu')(input_layer)
    x = tf.keras.layers.Dropout(0.2)(x)
    x = tf.keras.layers.Dense(32, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.2)(x)
    return tf.keras.Model(inputs=input_layer, outputs=x)

In [123]:
# Crear la rama izquierda y derecha de la red siamesa
left_input = tf.keras.layers.Input(shape=(input_shape,))
right_input = tf.keras.layers.Input(shape=(input_shape,))

left_branch = create_siamese_branch(input_shape)(left_input)
right_branch = create_siamese_branch(input_shape)(right_input)

In [124]:
# Concatenar las salidas de ambas ramas
merged = tf.keras.layers.Concatenate()([left_branch, right_branch])

In [125]:
# Agregar capas adicionales y la capa de salida
x = tf.keras.layers.Dense(32, activation='relu')(merged)
x = tf.keras.layers.Dropout(0.2)(x)
output = tf.keras.layers.Dense(13, activation='softmax')(x)

In [126]:
# Construir el modelo
model = tf.keras.Model(inputs=[left_input, right_input], outputs=output)

In [127]:
# Compilar el modelo
model.compile(optimizer='adam', loss=losses.SparseCategoricalCrossentropy(), metrics=['accuracy'])


In [128]:
# Entrenar el modelo
history = model.fit([X_train, X_train], y_train, epochs=100, batch_size=16, validation_split=0.2)


Epoch 1/100
10/10 [==============================] - 1s 30ms/step - loss: 2.6556 - accuracy: 0.0915 - val_loss: 2.4739 - val_accuracy: 0.2308
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 2.4073 - accuracy: 0.1765 - val_loss: 2.2776 - val_accuracy: 0.2821
Epoch 3/100
10/10 [==============================] - 0s 5ms/step - loss: 2.2106 - accuracy: 0.2810 - val_loss: 2.1119 - val_accuracy: 0.4359
Epoch 4/100
10/10 [==============================] - 0s 6ms/step - loss: 2.0191 - accuracy: 0.3856 - val_loss: 1.9413 - val_accuracy: 0.5128
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 1.8903 - accuracy: 0.4314 - val_loss: 1.7615 - val_accuracy: 0.6154
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 1.6302 - accuracy: 0.4967 - val_loss: 1.5568 - val_accuracy: 0.6667
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 1.4559 - accuracy: 0.6013 - val_loss: 1.3756 - val_accuracy: 0.6923
Epoch 8/100


Epoch 59/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0896 - accuracy: 0.9804 - val_loss: 0.7064 - val_accuracy: 0.8974
Epoch 60/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0936 - accuracy: 0.9804 - val_loss: 0.6959 - val_accuracy: 0.8974
Epoch 61/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0703 - accuracy: 0.9869 - val_loss: 0.6732 - val_accuracy: 0.8974
Epoch 62/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0981 - accuracy: 0.9739 - val_loss: 0.6741 - val_accuracy: 0.9231
Epoch 63/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0823 - accuracy: 0.9673 - val_loss: 0.6783 - val_accuracy: 0.9231
Epoch 64/100
10/10 [==============================] - 0s 5ms/step - loss: 0.1029 - accuracy: 0.9673 - val_loss: 0.6475 - val_accuracy: 0.9231
Epoch 65/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0880 - accuracy: 0.9673 - val_loss: 0.6350 - val_accuracy: 0.9231
Epoch 

In [129]:
# Cargar datos desde CSV
data = pd.read_csv('C:/Users/LEHI/Documents/Practicas profesionales/ABRIL/preprocessed data 33 columnas - etiqueta letras.csv')


In [130]:
# Convertir etiquetas a números
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [131]:
# Dividir datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Normalizar los datos (opcional pero recomendado)
X_train = (X_train - X_train.mean()) / X_train.std()
X_test = (X_test - X_test.mean()) / X_test.std()


In [132]:
# Evaluar el modelo
y_pred = model.predict([X_test, X_test])
y_pred_classes = np.argmax(y_pred, axis=1)

2/2 [==============================] - 0s 2ms/step


In [133]:
# Matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred_classes)
print("Matriz de Confusión:")
print(conf_matrix)

Matriz de Confusión:
[[3 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 1 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 1 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0 0 0]
 [0 0 0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 5 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 7]]


In [134]:
#Metricas

with np.errstate(divide='ignore', invalid='ignore'):
    # Exactitud (Accuracy)
    accuracy = np.sum(np.diag(conf_matrix)) / np.sum(conf_matrix)
    print("Exactitud (Accuracy):\n", accuracy)

    # Precisión (Precision)
    precision = np.diag(conf_matrix) / np.sum(conf_matrix, axis=0)
    precision[np.isnan(precision)] = 0  # Reemplaza NaN con 0
    print("Precisión (Precision) por clase:\n", precision)

    # Sensibilidad (Recall)
    sensibilidad = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)
    sensibilidad[np.isnan(sensibilidad)] = 0  # Reemplaza NaN con 0
    print("Sensibilidad (Recall) por clase:\n", sensibilidad)

    # Puntuación F1 (F1 Score)
    f1_score = 2 * (precision * sensibilidad) / (precision + sensibilidad)
    f1_score[np.isnan(f1_score)] = 0  # Reemplaza NaN con 0
    print("Puntuación F1 (F1 Score) por clase:\n", f1_score)

Exactitud (Accuracy):
 0.9375
Precisión (Precision) por clase:
 [1.         1.         0.75       1.         0.8        1.
 1.         0.66666667 1.         1.         1.         1.        ]
Sensibilidad (Recall) por clase:
 [1.         0.66666667 1.         0.85714286 1.         1.
 1.         1.         1.         1.         0.5        1.        ]
Puntuación F1 (F1 Score) por clase:
 [1.         0.8        0.85714286 0.92307692 0.88888889 1.
 1.         0.8        1.         1.         0.66666667 1.        ]
